local XGEN_MULTICHARACTER = RESOURCE_LOAD(SIM, "src/main/Content/Script/xgen-multicharacter")
RESOURCE_START(XGEN_MULTICHARACTER)
table.insert(RESOURCES, XGEN_MULTICHARACTER)

local environment = ENVIRONMENT_GET(SERVER, XGEN_MULTICHARACTER)
