site_name: XGen - Framework - Documentation
site_url: https://XGEN-OSC.github.io/XGen-Framework
theme:
  name: material

nav:
  - Home: index.md
  - API:
    - DBSC: api/dbsc.md
    - XTransaction: api/xtransaction.md
    - XPlayer: api/xplayer.md
    - XCharacter: api/xcharacter.md
    - XAccount: api/xaccount.md
    - Database: api/database.md